name: Compress image

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compress image
        uses: ./.github/action-compress-image/
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "[gh-actions] compress image"
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
